import { createClient } from 'npm:@supabase/supabase-js@2';
const H={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-session-token','Access-Control-Allow-Methods':'POST,OPTIONS'};
const R=(o:any,s=200)=>new Response(JSON.stringify(o),{status:s,headers:{...H,'Content-Type':'application/json'}});
const token=(r:Request)=>(r.headers.get('x-session-token')||r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();
const app=(v:any):'VetMap'|'TarMap'|null=>v==='VetMap'||v==='TarMap'?v:null;
const pass=()=>{const c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const b=new Uint32Array(16);crypto.getRandomValues(b);return Array.from(b,n=>c[n%c.length]).join('')};
async function telegram(a:'VetMap'|'TarMap',id:string,u:string,p:string){const k=Deno.env.get('TELEGRAM_BOT_TOKEN_AGE');if(!k)throw Error('Telegram bot secret eksik');const r=await fetch(`https://api.telegram.org/bot${k}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:id,text:`${a} hesabınız için geçici şifre oluşturuldu.\nKullanıcı adı: ${u}\nGeçici şifre: ${p}\n\nİlk girişten sonra şifrenizi değiştirmeniz önerilir.`})});const x=await r.json().catch(()=>null);if(!r.ok||!x?.ok)throw Error('Telegram gönderimi başarısız')}
Deno.serve(async r=>{if(r.method==='OPTIONS')return new Response('ok',{headers:H});if(r.method!=='POST')return R({basarili:false,mesaj:'Yalnızca POST desteklenir'},405);try{const b=await r.json(),a=app(b.uygulama_adi),t=token(r),x=String(b.islem||'').trim();if(!a||!t)return R({basarili:false,mesaj:'Oturum veya uygulama bilgisi eksik'},401);const u=Deno.env.get('SUPABASE_URL'),k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!u||!k)throw Error('Supabase sunucu anahtarı eksik');const s=createClient(u,k,{auth:{persistSession:false}}),q={p_token:t,p_uygulama_adi:a};let d:any,e:any;
if(x==='listele')({data:d,error:e}=await s.rpc('admin_kullanici_listesi',q));
else if(x==='guncelle')({data:d,error:e}=await s.rpc('admin_kullanici_guncelle',{...q,p_kullanici_id:b.kullanici_id,p_tarmap_yetkisi:!!b.tarmap_yetkisi,p_vetmap_yetkisi:!!b.vetmap_yetkisi,p_telegram_id:b.telegram_id?String(b.telegram_id).trim():null}));
else if(x==='sil')({data:d,error:e}=await s.rpc('admin_kullanici_sil',{...q,p_kullanici_id:b.kullanici_id}));
else if(x==='ekle'||x==='sifre_sifirla'){const p=pass();if(x==='ekle'){const n=String(b.kullanici_adi||'').trim(),id=String(b.telegram_id||'').trim();if(!n||!id||id==='---')return R({basarili:false,mesaj:'Kullanıcı adı ve Telegram ID zorunludur'},400);({data:d,error:e}=await s.rpc('admin_kullanici_ekle',{...q,p_kullanici_adi:n,p_gecici_sifre:p,p_tarmap_yetkisi:!!b.tarmap_yetkisi,p_vetmap_yetkisi:!!b.vetmap_yetkisi,p_telegram_id:id}));if(e||!d?.basarili)return R({basarili:false,mesaj:d?.mesaj||'Kullanıcı oluşturulamadı'},400);try{await telegram(a,id,n,p)}catch(_){return R({basarili:false,mesaj:'Kullanıcı oluşturuldu ancak Telegram gönderilemedi'},502)}return R({basarili:true,mesaj:'Kullanıcı oluşturuldu ve geçici şifre Telegram ile gönderildi'})}({data:d,error:e}=await s.rpc('admin_sifre_sifirla',{...q,p_kullanici_id:b.kullanici_id,p_gecici_sifre:p}));if(e||!d?.basarili)return R({basarili:false,mesaj:d?.mesaj||'Şifre yenilenemedi'},400);const id=String(d.telegram_id||'').trim(),n=String(d.kullanici_adi||'').trim();if(!id||!n)return R({basarili:false,mesaj:'Telegram hedefi bulunamadı'},502);try{await telegram(a,id,n,p)}catch(_){return R({basarili:false,mesaj:'Şifre yenilendi ancak Telegram gönderilemedi'},502)}return R({basarili:true,mesaj:'Yeni geçici şifre Telegram ile gönderildi'})}
else return R({basarili:false,mesaj:'Geçersiz yönetici işlemi'},400);if(e)return R({basarili:false,mesaj:'Yönetici işlemi gerçekleştirilemedi'},400);return R(d||{basarili:true})}catch(e){console.error('admin-yonetim:',e instanceof Error?e.message:'sunucu hatası');return R({basarili:false,mesaj:'Yönetici işlemi sırasında sunucu hatası oluştu'},500)}});
